# Generated by Django 4.1.7 on 2023-08-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reliance', '0004_order_customer_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
